CREATE TABLE CLOCK_TYPES(
IDCLOCK NUMBER(2) PRIMARY KEY,
C_TYPE VARCHAR2(10) UNIQUE);

CREATE TABLE EMPLOYEES(
ID NUMBER(4) PRIMARY KEY,
NAME VARCHAR2(40) NOT NULL,
PASSWORD VARCHAR2(50) NOT NULL);

CREATE TABLE CHECKS(
IDEMP NUMBER(4),
IDCLOCK NUMBER NOT NULL,
CLOCKTYPE NUMBER(2),
TIME DATE NOT NULL,
PRIMARY KEY(IDEMP, IDCLOCK),
FOREIGN KEY (IDEMP) REFERENCES EMPLOYEES(ID),
FOREIGN KEY (CLOCKTYPE) REFERENCES CLOCK_TYPES(IDCLOCK));

INSERT INTO CLOCK_TYPES VALUES(1, 'START');
INSERT INTO CLOCK_TYPES VALUES(2, 'END');
