CREATE TABLE PRODUCTOS(
    IDPRODUCTO NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(50),
    STOCKACTUAL NUMBER,
    STOCKMINIMO NUMBER,
    PVP NUMBER(*,2)
);

CREATE TABLE PEDIDOS(
    IDPEDIDO NUMBER PRIMARY KEY,
    IDPRODUCTO NUMBER,
    FECHA DATE,
    CANTIDAD NUMBER,
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO)
);

CREATE TABLE VENTAS(
    NROVENTA NUMBER PRIMARY KEY,
    IDPRODUCTO NUMBER,
    FECHA DATE,
    CANTIDAD NUMBER,
    OBSERVACIONES VARCHAR2(50),
    FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO)
);

INSERT INTO PRODUCTOS VALUES(1, 'RATON USB', 10, 5, 5.60);
COMMIT;

