CREATE TABLE USERS(
LOGIN VARCHAR2(30) PRIMARY KEY,
PASSWORD VARCHAR2(16) NOT NULL);

INSERT INTO USERS VALUES('user1','pass1');
INSERT INTO USERS VALUES('user2','pass2');
INSERT INTO USERS VALUES('user3','pass3');
INSERT INTO USERS VALUES('user4','pass4');
INSERT INTO USERS VALUES('user5','pass5');

COMMIT;